# bitcoin_node_deploy.yml
# Initial raw configuration
- hosts: 127.0.0.1
  connection: local
  become: yes
  gather_facts: no
  user: ubuntu
  roles:
    - role: ubuntu.raw_install_python

- hosts: 127.0.0.1
  connection: local
  become: yes
  gather_facts: yes
  user: ubuntu
  roles:
    - role: instance.ssh_aws_public_key
    - role: instance.packages
    - role: instance.docker
    - role: instance.prometheus_node_exporter
    - role: instance.bitcoind
      tags:
        - bit
    - role: instance.bitcoind_automated_updates
